Io 20110905
Io> loop("getting dizzy...")
getting dizzy...
getting dizzy...
getting dizzy...
...
getting dizzy...
getting dizzy...
getting dizzy...
IOVM:
        Received signal. Setting interrupt flag.


  current coroutine
  ---------
  Coroutine callStack                  A4_Exception.io 244
  Coroutine backTraceString            A4_Exception.io 274
  Coroutine showStack                  System.io 62
  System userInterruptHandler          [unlabeled] 0
