diancang@diancang /cygdrive/d/codes/guiwuu/notes_of_7l7w/4-scala/day3
$ scala 3-actor.scala 
Ready to poke and feed...
Ow...
Ow...
Quit it...
Quit it...
Gurgle...
Burp...
Gurgle...
Burp...

diancang@diancang /cygdrive/d/codes/guiwuu/notes_of_7l7w/4-scala/day3
$ scala 3-actor.scala 
Ready to poke and feed...
Ow...
Ow...
Quit it...
Quit it...
Gurgle...
Gurgle...
Burp...
Burp...